name: 00010 Ktor Hello

on:
  push:
    paths:
      - ".github/workflows/00010_ktor_hello.yml"
      - "./00010_ktor_hello/**"

defaults:
  run:
    working-directory: 00010_ktor_hello

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew clean test

      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test results
          path: 00010_ktor_hello/build/test-results/test/*.xml
          reporter: java-junit
